"""
MT5 Bridge — Application settings and configuration.
"""

from __future__ import annotations

from functools import lru_cache
from pathlib import Path
from typing import Any

import yaml
from pydantic import Field
from pydantic_settings import BaseSettings

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# MT5 timeframe constant mapping.
MT5_TIMEFRAME_MAP: dict[str, int] = {
    "M1": 1,
    "M5": 5,
    "M15": 15,
    "M30": 30,
    "H1": 16385,
    "H4": 16388,
    "D1": 16408,
    "W1": 32769,
    "MN1": 49153,
}


class SymbolEntry:
    """Single entry in the symbol mapping table."""

    def __init__(self, mt5_symbol: str, lot_size: float, category: str) -> None:
        self.mt5_symbol = mt5_symbol
        self.lot_size = lot_size
        self.category = category

    def __repr__(self) -> str:
        return f"SymbolEntry({self.mt5_symbol!r}, lot={self.lot_size}, cat={self.category!r})"


class Settings(BaseSettings):
    # Bridge server
    mt5_bridge_port: int = Field(default=8001, alias="MT5_BRIDGE_PORT")
    mt5_bridge_api_key: str = Field(default="change-me", alias="MT5_BRIDGE_API_KEY")

    # MT5 credentials
    mt5_login: int | None = Field(default=None, alias="MT5_LOGIN")
    mt5_password: str | None = Field(default=None, alias="MT5_PASSWORD")
    mt5_server: str = Field(default="Deriv-Demo", alias="MT5_SERVER")
    mt5_path: str | None = Field(default=None, alias="MT5_PATH")

    # Runtime policy
    execution_enabled: bool = Field(default=False, alias="EXECUTION_ENABLED")
    metrics_retention_days: int = Field(default=90, alias="METRICS_RETENTION_DAYS")
    multi_trade_overload_queue_threshold: int = Field(
        default=100, alias="MULTI_TRADE_OVERLOAD_QUEUE_THRESHOLD"
    )
    max_pre_dispatch_slippage_pct: float = Field(default=1.0, alias="MAX_PRE_DISPATCH_SLIPPAGE_PCT")
    max_post_fill_slippage_pct: float = Field(default=1.0, alias="MAX_POST_FILL_SLIPPAGE_PCT")

    # Paths / logging
    symbols_config_path: str = Field(default="config/symbols.yaml", alias="SYMBOLS_CONFIG_PATH")
    runtime_state_path: str = Field(default="logs/bridge/runtime_state.json", alias="RUNTIME_STATE_PATH")
    log_level: str = Field(default="INFO", alias="LOG_LEVEL")

    # Test support
    disable_mt5_worker: bool = Field(default=False, alias="DISABLE_MT5_WORKER")

    # Broker capabilities cache (feature 008-adaptive-broker-capabilities)
    capabilities_cache_ttl_seconds: int = Field(
        default=60,
        alias="CAPABILITIES_CACHE_TTL_SECONDS",
        description="How long (in seconds) the broker capabilities cache is valid before re-fetching from MT5",
    )
    auto_select_symbols: bool = Field(
        default=True,
        alias="AUTO_SELECT_SYMBOLS",
        description="Automatically select symbols in MT5 Market Watch when scanning the broker catalog",
    )

    # Readiness checks (feature 011-phase2-readiness-and-prerequisites)
    tick_freshness_threshold_seconds: int = Field(
        default=30,
        alias="TICK_FRESHNESS_THRESHOLD_SECONDS",
        description="Maximum age (seconds) for a tick before readiness flags it as stale",
    )

    # Execution hardening (feature 012-phase3-execution-hardening)
    idempotency_ttl_seconds: int = Field(
        default=3600,
        alias="IDEMPOTENCY_TTL_SECONDS",
        description="Lifetime in seconds for idempotency cache entries",
    )
    strict_http_semantics: bool = Field(
        default=False,
        alias="STRICT_HTTP_SEMANTICS",
        description="When True, business failures return 4xx/5xx instead of HTTP 200",
    )

    # Launcher integration (feature 014-phase5-launcher-runtime-hardening)
    launcher_run_id: str | None = Field(
        default=None,
        alias="LAUNCHER_RUN_ID",
        description="The unique run ID generated by the launcher script",
    )

    # Conformance and Compatibility Profiles (feature 016-phase7-native-parity-surface-and-conformance)
    compatibility_profile: str = Field(
        default="strict_safe",
        alias="COMPATIBILITY_PROFILE",
    )

    model_config = {"env_file": ".env", "extra": "ignore"}


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()


def load_symbol_map(config_path: str | Path | None = None) -> dict[str, SymbolEntry]:
    if config_path is None:
        settings = Settings()
        config_path = settings.symbols_config_path

    cfg = Path(config_path)
    if not cfg.is_absolute():
        cfg = PROJECT_ROOT / cfg

    if not cfg.exists():
        raise FileNotFoundError(f"Symbol map not found at {cfg}")

    with cfg.open("r", encoding="utf-8") as fh:
        raw: dict[str, Any] = yaml.safe_load(fh) or {}

    entries: dict[str, SymbolEntry] = {}
    for ticker, info in raw.get("symbols", {}).items():
        entries[ticker] = SymbolEntry(
            mt5_symbol=info["mt5_symbol"],
            lot_size=float(info.get("lot_size", 0.01)),
            category=str(info.get("category", "unknown")),
        )
    return entries


def get_mt5_timeframe(tf_string: str) -> int:
    tf_upper = tf_string.upper()
    if tf_upper not in MT5_TIMEFRAME_MAP:
        valid = ", ".join(sorted(MT5_TIMEFRAME_MAP.keys()))
        raise ValueError(f"Unknown timeframe '{tf_string}'. Valid: {valid}")
    return MT5_TIMEFRAME_MAP[tf_upper]


_last_loaded_profile: str | None = None

def get_compatibility_profile() -> "CompatibilityProfile":
    """
    Loads the compatibility profiles YAML and returns the matching CompatibilityProfile 
    instance for the current COMPATIBILITY_PROFILE setting.
    """
    from app.models.compatibility import CompatibilityProfile

    settings = get_settings()
    profile_name = settings.compatibility_profile

    cfg = PROJECT_ROOT / "config" / "compatibility-profiles.yaml"
    
    if not cfg.exists():
        # Fallback to defaults if the file is missing
        return CompatibilityProfile(
            name=profile_name,
            retry_aggressiveness="low",
            optional_field_handling="drop",
            gating_strictness="high",
            warning_verbosity="low"
        )

    with cfg.open("r", encoding="utf-8") as fh:
        raw: dict[str, Any] = yaml.safe_load(fh) or {}

    profiles_data = raw.get("profiles", {})
    
    if profile_name not in profiles_data:
        # Fallback to strict_safe if invalid profile specified
        profile_data = profiles_data.get("strict_safe", {
            "retry_aggressiveness": "low",
            "optional_field_handling": "drop",
            "gating_strictness": "high",
            "warning_verbosity": "low"
        })
        profile_name = "strict_safe"
    else:
        profile_data = profiles_data[profile_name]

    global _last_loaded_profile
    if _last_loaded_profile is not None and _last_loaded_profile != profile_name:
        from app.audit import log_task_event
        log_task_event(
            "compatibility_profile_changed",
            request=None,
            outcome="success",
            status_code=200,
            details={
                "old_profile": _last_loaded_profile,
                "new_profile": profile_name
            }
        )
    _last_loaded_profile = profile_name

    return CompatibilityProfile(
        name=profile_name,
        retry_aggressiveness=profile_data.get("retry_aggressiveness", "low"),
        optional_field_handling=profile_data.get("optional_field_handling", "drop"),
        gating_strictness=profile_data.get("gating_strictness", "high"),
        warning_verbosity=profile_data.get("warning_verbosity", "low"),
    )
